FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps
RUN npm install terser --legacy-peer-deps

COPY . .
RUN --mount=type=secret,id=vite_env,target=/app/.env.local \
    npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]