FROM ubuntu AS build

COPY . .

RUN apt-get update && apt-get install -y openjdk-21-jdk && chmod +x gradlew 

RUN ./gradlew wrapper --gradle-version 8.7

RUN ./gradlew build

FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

COPY --from=build /app/build/libs/*.jar app.jar

EXPOSE 9091

ENTRYPOINT ["java", "-jar", "app.jar"]