/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import io.github.cdimascio.dotenv.Dotenv;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.context.annotation.Bean;
import org.springframework.scheduling.annotation.EnableAsync;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.web.client.RestTemplate;

@SpringBootApplication
@EnableTransactionManagement
@EnableAsync
@EnableCaching
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);

    }
    @Bean
    public RestTemplate restTemplate(){
        return   new RestTemplate();
    }
}
